# .github/workflows/deploy-react-ghpages.yml
name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # This workflow runs when changes are pushed to the main branch
  workflow_dispatch: # Allows manual triggering from the Actions tab

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use a Linux runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checkout the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" # Use Node.js version 18 or higher (adjust if needed)
          cache: "npm" # Cache npm dependencies for faster builds

      - name: Install dependencies
        run: npm install # Install your project's npm dependencies

      - name: Build React app
        run: npm run build # Run the React build command to create the 'build' folder

      # --- GitHub Pages specific actions ---
      - name: Setup Pages
        uses: actions/configure-pages@v5 # Configures GitHub Pages environment
        # This action sets up the GITHUB_PAGES_URL and GITHUB_PAGES_BUILD_BASE_PATH
        # which are crucial for React Router if you were using it.
        # For your current setup, it ensures the base path is handled correctly.

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the 'build' directory, which contains your compiled React app
          path: "./build"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Deploys the uploaded artifact to GitHub Pages
